sudo: false
language: ruby
addons:
  apt:
    packages:
    - asciidoc
    - libxml2-utils
    - xsltproc
    - docbook-xsl
    - ca-certificates
rvm: 2.1.0
env:
  - PUPPET_VERSION=3.5
script:
  - bundle exec rake build PREFIX=/ SYSCONFDIR=/etc
  - INSTDIR=$(mktemp -d)
  - bundle exec rake install PREFIX=$INSTDIR
  - bundle exec $INSTDIR/sbin/foreman-installer --help
  # No references to INSTDIR should be present when built with PREFIX=/
  - grep -rv $INSTDIR $INSTDIR
  - find $INSTDIR -type l -printf '%P: ' -exec readlink {} \; | grep -v $INSTDIR
